# Generated by Django 5.1.3 on 2024-11-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0003_pack_delete_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Package name')),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=150, verbose_name='Package Details')),
                ('cat', models.IntegerField(choices=[(1, 'By Plane'), (2, 'By Train'), (3, 'By Bus')], verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
            ],
        ),
        migrations.DeleteModel(
            name='pack',
        ),
    ]
