# Generated by Django 5.1.3 on 2024-11-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0005_packages_delete_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='packages',
        ),
    ]
