# Generated by Django 5.1.3 on 2024-11-07 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='to_date',
        ),
        migrations.AddField(
            model_name='package',
            name='contact_no',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
